# 拾光豆（ShinePod）Docker Compose配置
version: '3.8'

services:
  shinepod-backend:
    build: .
    container_name: shinepod-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shinepod-network

  shinepod-mobile-app:
    build: .
    container_name: shinepod-mobile-app
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOST=0.0.0.0
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - shinepod-backend
    networks:
      - shinepod-network

  nginx:
    image: nginx:alpine
    container_name: shinepod-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - shinepod-backend
      - shinepod-mobile-app
    restart: unless-stopped
    networks:
      - shinepod-network

networks:
  shinepod-network:
    driver: bridge

volumes:
  shinepod-data:
  shinepod-logs: